# Site settings
title: DevScrapbook
header-img: img/home-bg.png
email: breyanna.bvass@gmail.com
copyright_name: newedition994
description: > # this means to ignore newlines until "baseurl:"
  Scrapbooking my experiences while learning code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  newedition994
learn_profile: newedition994
email_username: breyanna.bvass@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
